version: 0.2
env:
  shell: bash
  variables: {}
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - sudo rm -rf /usr/local/lib/android & sudo rm -rf /usr/share/dotnet & sudo rm -rf /opt/ghc
      - yum -y install wget || apt-get -y install wget
      - _MINICONDA_ARCHIVE_URL=https://repo.anaconda.com/miniconda
      - export LCC_MINICONDA_INSTALLER=Miniconda3-latest-Linux-x86_64.sh
      - export LCC_MINICONDA_INSTALLER_URL=$_MINICONDA_ARCHIVE_URL/$LCC_MINICONDA_INSTALLER
      - export LCC_MINICONDA_INSTALL_DIR=$HOME/Braket/miniconda3
      - wget --quiet $LCC_MINICONDA_INSTALLER_URL --output-document $LCC_MINICONDA_INSTALLER
      - chmod a+x $LCC_MINICONDA_INSTALLER
      - ./$LCC_MINICONDA_INSTALLER -b -p $LCC_MINICONDA_INSTALL_DIR
  pre_build:
    commands:
      - echo "Setting up conda"
      - export PATH=$LCC_MINICONDA_INSTALL_DIR/bin:$PATH
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
      - export CONDA_THREADS=$(nproc)
      - conda config --set default_threads $CONDA_THREADS
      - conda config --set channel_priority strict
      - conda config --set solver libmamba
      - conda install -y -q --freeze-installed -c conda-forge conda-pack=0.8.1 squashfs-tools
  build:
    commands:
      - BRAKET_ENV=Braket
      - mkdir -p envs
      - conda config --set path_conflict warn
      - conda env create -q --name $BRAKET_ENV -f environment.yml --no-default-package --solver libmamba
      - pip cache purge
      - conda clean --all --yes --quiet
      - _ENV_PATH=$LCC_MINICONDA_INSTALL_DIR/envs/$BRAKET_ENV
      - |
        find $_ENV_PATH/lib/python*/site-packages -type d \( -name "tests" -o -name "test" \) | \
        grep -v "amazon_braket" | \
        grep -v "braket" | \
        grep -v "numpy" | \
        xargs rm -rf 2>/dev/null || true
      - echo "Creating SquashFS image with conda-pack..."
      - conda pack --quiet --name $BRAKET_ENV --output envs/Braket.tar.zst 
          --compress-level 3 --n-threads -1 --ignore-missing-files
      - conda pack --name $BRAKET_ENV --output envs/Braket.sqfs
          --format squashfs
          --n-threads -1
          --compress-level 9
          --ignore-missing-files
          --exclude "*.pyc" --exclude "*.pyo" --exclude "__pycache__/*"
          --exclude "share/man/*" --exclude "share/doc/*" --exclude "share/info/*"
      - echo "SquashFS image size:"
      - du -hs envs/Braket.sqfs
      - ls -lh envs/Braket.sqfs
      - echo "Archive size:"
      - du -hs envs/Braket.tar.zst

artifacts:
  files:
    - envs/Braket.sqfs
    - envs/Braket.tar.zst
    - environment.yml
    - requirements.txt
  name: CONDA_BUILD_RESULTS
