version: 0.2
env:
  shell: bash
  variables: {}
phases:
  build:
    commands:
      - mkdir envs
      - echo "Hello There" >> envs/Braket.tgz

artifacts:
  files:
    - envs/Braket.tgz
  name: CONDA_BUILD_RESULTS
