version: 0.2
env:
  shell: bash
  variables: {}
phases:
  install:
    commands:
      - _ANACONDA_ARCHIVE_URL=https://repo.anaconda.com/archive
      - _MINICONDA_ARCHIVE_URL=https://repo.anaconda.com/miniconda
      - export LCC_MINICONDA_INSTALLER=Miniconda3-py311_23.5.2-0-Linux-x86_64.sh
      - export LCC_MINICONDA_INSTALLER_URL=$_MINICONDA_ARCHIVE_URL/$LCC_MINICONDA_INSTALLER
      - export LCC_MINICONDA_INSTALLER_SHA256=634d76df5e489c44ade4085552b97bebc786d49245ed1a830022b0b406de5817
      - export LCC_MINICONDA_INSTALL_DIR=$HOME/Braket/miniconda3
      - wget --quiet $LCC_MINICONDA_INSTALLER_URL --output-document $LCC_MINICONDA_INSTALLER
      - echo "$LCC_MINICONDA_INSTALLER_SHA256  $LCC_MINICONDA_INSTALLER" | sha256sum --status --check -
      - chmod a+x $LCC_MINICONDA_INSTALLER
      - ./$LCC_MINICONDA_INSTALLER -b -p $LCC_MINICONDA_INSTALL_DIR
  pre_build:
    commands:
      - echo "Setting up conda"
      - export PATH=$LCC_MINICONDA_INSTALL_DIR/bin:$PATH
      - conda config --set default_threads 2
      - conda config --set channel_priority strict
      - conda install -q conda-libmamba-solver
      - conda config --set solver libmamba
      - conda install -q -c conda-forge conda-pack=0.7.0
  build:
    commands:
      - BRAKET_ENV=Braket
      - mkdir -p envs
      - conda config --set path_conflict warn
      - conda env create --name $BRAKET_ENV -f environment.yml --no-default-package --solver libmamba
      - conda clean --all
      - conda pack --quiet --name $BRAKET_ENV --output envs/Braket.tgz --compress-level 9 --n-threads -1

artifacts:
  files:
    - envs/Braket.tgz
    - environment.yml
    - requirements.txt
  name: CONDA_BUILD_RESULTS
