version: 0.2
env:
  shell: bash
  variables: {}
phases:
  install:
    commands:
      - _ANACONDA_ARCHIVE_URL=https://repo.anaconda.com/archive
      - _MINICONDA_ARCHIVE_URL=https://repo.anaconda.com/miniconda
      - export LCC_CONDA_INSTALLER=Anaconda3-2020.07-Linux-x86_64.sh
      - export LCC_CONDA_INSTALLER_URL=$_ANACONDA_ARCHIVE_URL/$LCC_CONDA_INSTALLER
      - export LCC_CONDA_INSTALLER_MD5=1046c40a314ab2531e4c099741530ada
      - export LCC_CONDA_INSTALL_DIR=$HOME/Braket/anaconda3
      - wget --quiet $LCC_CONDA_INSTALLER_URL --output-document $LCC_CONDA_INSTALLER
      - echo "$LCC_CONDA_INSTALLER_MD5  $LCC_CONDA_INSTALLER" | md5sum --status --check -
      - chmod a+x $LCC_CONDA_INSTALLER
      - ./$LCC_CONDA_INSTALLER -b -p $LCC_CONDA_INSTALL_DIR
  pre_build:
    commands:
      - echo "Setting up conda"
      - export PATH=$LCC_CONDA_INSTALL_DIR/bin:$PATH
      - for CHANNEL in conda-forge cf-staging; do conda config --system --append channels $CHANNEL; done
      - conda install --yes conda-pack
  build:
    commands:
      - BRAKET_ENV=Braket
      - mkdir -p envs
      - conda config --set path_conflict warn
      - conda env create --name $BRAKET_ENV -f environment.yml
      - conda pack --name $BRAKET_ENV --output envs/Braket.tgz

artifacts:
  files:
    - envs/Braket.tgz
    - environment.yml
  name: CONDA_BUILD_RESULTS