version: 0.2
env:
  shell: bash
  variables: {}
phases:
  install:
    commands:
      - sudo rm -rf /usr/local/lib/android & sudo rm -rf /usr/share/dotnet & sudo rm -rf /opt/ghc
      - yum -y install wget squashfs-tools || apt-get -y install wget squashfs-tools
      - _MINICONDA_ARCHIVE_URL=https://repo.anaconda.com/miniconda
      - export LCC_MINICONDA_INSTALLER=Miniconda3-latest-Linux-x86_64.sh
      - export LCC_MINICONDA_INSTALLER_URL=$_MINICONDA_ARCHIVE_URL/$LCC_MINICONDA_INSTALLER
      - export LCC_MINICONDA_INSTALL_DIR=$HOME/Braket/miniconda3
      - wget --quiet $LCC_MINICONDA_INSTALLER_URL --output-document $LCC_MINICONDA_INSTALLER
      - chmod a+x $LCC_MINICONDA_INSTALLER
      - ./$LCC_MINICONDA_INSTALLER -b -p $LCC_MINICONDA_INSTALL_DIR
  pre_build:
    commands:
      - echo "Setting up conda"
      - export PATH=$LCC_MINICONDA_INSTALL_DIR/bin:$PATH
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
      - export CONDA_THREADS=$(nproc)
      - conda config --set default_threads $CONDA_THREADS
      - conda config --set channel_priority strict
      - conda config --set solver libmamba
  build:
    commands:
      - BRAKET_ENV=Braket
      - mkdir -p envs
      - conda config --set path_conflict warn
      - conda env create -q --name $BRAKET_ENV -f environment.yml --no-default-package --solver libmamba
      - pip cache purge
      - conda clean --all --yes --quiet
      - _ENV_PATH=$LCC_MINICONDA_INSTALL_DIR/envs/$BRAKET_ENV
      - |
        find $_ENV_PATH/lib/python*/site-packages -type d \( -name "tests" -o -name "test" \) | \
        grep -v "amazon_braket" | \
        grep -v "braket" | \
        xargs rm -rf 2>/dev/null || true
      - echo "Creating SquashFS image..."
      - |
        mksquashfs $_ENV_PATH envs/Braket.sqfs \
          -comp zstd \
          -Xcompression-level 19 \
          -b 1M \
          -no-xattrs \
          -no-exports \
          -e "*.pyc" "*.pyo" "__pycache__" \
          "share/man" "share/doc" "share/info" \
          "*.a" "*.la" \
          -processors $(nproc) \
          -progress
      - echo "SquashFS image created successfully"
      - du -hs envs/Braket.sqfs
      - ls -lh envs/Braket.sqfs

artifacts:
  files:
    - envs/Braket.sqfs
    - environment.yml
    - requirements.txt
  name: CONDA_BUILD_RESULTS
