version: 0.2
env:
  shell: bash
  variables: {}
phases:
  install:
    commands:
      - yum -y install wget || apt-get -y install wget
      - _ANACONDA_ARCHIVE_URL=https://repo.anaconda.com/archive
      - _MINICONDA_ARCHIVE_URL=https://repo.anaconda.com/miniconda
      # Newer Miniconda versions require newer glibc
      - export LCC_MINICONDA_INSTALLER=Miniconda3-py313_25.7.0-2-Linux-x86_64.sh
      - export LCC_MINICONDA_INSTALLER_URL=$_MINICONDA_ARCHIVE_URL/$LCC_MINICONDA_INSTALLER
      - export LCC_MINICONDA_INSTALL_DIR=$HOME/Braket/miniconda3
      - wget --quiet $LCC_MINICONDA_INSTALLER_URL --output-document $LCC_MINICONDA_INSTALLER
      - chmod a+x $LCC_MINICONDA_INSTALLER
      - ./$LCC_MINICONDA_INSTALLER -b -p $LCC_MINICONDA_INSTALL_DIR
  pre_build:
    commands:
      - echo "Setting up conda"
      - export PATH=$LCC_MINICONDA_INSTALL_DIR/bin:$PATH
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
      - conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
      - conda config --set default_threads 2
      - conda config --set channel_priority strict
      - conda config --set solver libmamba
      - conda install -y -q --freeze-installed -c conda-forge conda-pack=0.7.1
  build:
    commands:
      - BRAKET_ENV=Braket
      - mkdir -p envs
      - conda config --set path_conflict warn
      # Diagnostics: glibc, system, python/pip visibility, and pip index for cuda-quantum-cu12
      - echo "glibc:" && (ldd --version 2>&1 | head -n1) || true
      - echo "System info:" && uname -a || true
      - echo "Host python:" && python --version && which python || true
      - echo "Miniconda python (if installed):" && $LCC_MINICONDA_INSTALL_DIR/bin/python --version || true
      - export PATH=$LCC_MINICONDA_INSTALL_DIR/bin:$PATH
      - echo "Post-PATH python:" && python --version && which python || true
      - echo "pip info:" && pip --version || true
      - echo "pip debug:" && pip debug --verbose || true
      - echo "pip index versions for cuda-quantum-cu12:" && pip index versions cuda-quantum-cu12 || true
      - echo "attempt to pip install cuda-quantum-cu12==0.12.0.post1 (no deps, verbose):" && pip install --no-deps --verbose --no-cache-dir cuda-quantum-cu12==0.12.0.post1 || true
      - echo "PIP env vars:" && env | grep -i PIP || true
      - echo "/etc/os-release:" && cat /etc/os-release || true
      - conda env create --name $BRAKET_ENV -f environment.yml --no-default-package --solver libmamba
      - pip cache purge
      - conda pack --quiet --name $BRAKET_ENV --output envs/Braket.tar --compress-level 1 --n-threads -1
      - zstd -22 --ultra envs/Braket.tar -T0 --auto-threads=logical --rsyncable --sparse
      - du -hs envs/Braket.tar.zst

artifacts:
  files:
    - envs/Braket.tar.zst
    - environment.yml
    - requirements.txt
  name: CONDA_BUILD_RESULTS
