name: Publish distribution to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish distribution to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install wheel
        run: python -m pip install --user --upgrade wheel
      - name: Install twine
        run: python -m pip install --user --upgrade twine
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_token }}
