name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - jinja2==3.1.2
  - markupsafe
  - matplotlib
  - oqpy==0.2.1
  - numpy==1.23
  - pandas
  - scipy
  - pip:
    - urllib3==2.0.4
    - antlr4-python3-runtime==4.9.2
    - keras==2.12.0
    - setuptools
    - boltons
    - nest-asyncio
    - networkx
    - openpulse
    - openqasm3
    - opt-einsum==3.3.0
    - sympy==1.12
    - mpmath==1.3.0
    - pydantic==1.8.2
    - awscli
    - botocore
    - boto3
    - dask
    - amazon-braket-sdk
    - amazon-braket-schemas
    - amazon-braket-default-simulator
    - amazon-braket-pennylane-plugin
    - amazon-braket-algorithm-library
    - mypy-extensions==0.4.3
    - pennylane==0.31.0 
    - jax==0.4.2
    - qiskit_braket_provider==0.0.4