name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - jinja2==3.1.2
  - keras==2.12.0
  - markupsafe
  - matplotlib
  - oqpy==0.2.1
  - numpy==1.23
  - pandas
  - scipy
  - pip:
    - colorama >=0.2.5,<=0.3.7
    - awscli
    - docutils
    - botocore
    - boto3
    - s3transfer
    - distributed
    - dask
    - pydantic==1.9.0 
    - amazon-braket-sdk
    - amazon-braket-schemas
    - amazon-braket-default-simulator
    - amazon-braket-pennylane-plugin
    - amazon-braket-algorithm-library
    - mypy-extensions==0.4.3
    - pennylane==0.31.0 
    - openfermionpyscf==0.5
    - openfermion==1.5.1
    - jax==0.4.2
    - qiskit_braket_provider==0.0.4