name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - markupsafe
  - matplotlib
  - numpy >=1.17.3,<1.25.0
  - pandas
  - scipy
  - antlr4-python3-runtime==4.9.2
  - pip:
    - tornado
    - jinja2==3.1.2
    - oqpy==0.2.1
    - urllib3==2.0.4
    - keras==2.12.0
    - setuptools
    - boltons
    - nest-asyncio
    - networkx
    - openpulse
    - typing-extensions
    - opt-einsum==3.3.0
    - sympy==1.12
    - mpmath==1.3.0
    - pydantic==1.8.2
    - awscli==1.29.4
    - botocore==1.31.4
    - boto3==1.28.3
    - dask==2023.1.1
    - openqasm3
    - amazon-braket-sdk==1.54.2
    - amazon-braket-schemas==1.19.1
    - amazon-braket-default-simulator==1.20.0
    - amazon-braket-pennylane-plugin==1.20.1
    - amazon-braket-algorithm-library==1.4.1
    - mypy-extensions==0.4.3
    - pennylane==0.31.0 
    - jax==0.4.2
    - qiskit_braket_provider==0.0.4