name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - jinja2
  - keras
  - markupsafe
  - matplotlib
  - oqpy
  - numpy
  - pandas
  - scipy
  - s3transfer
  - botocore
  - boto3
  - pydantic==1.9.0
  - amazon-braket-schemas
  - amazon-braket-default-simulator
  - amazon-braket-pennylane-plugin
  - amazon-braket-sdk
  - amazon-braket-algorithm-library
  - cvxpy
  - ecos
  - mypy-extensions
  - PennyLane-Lightning
  - pennylane
  - qiskit-aer
  - qiskit_braket_provider
  - qiskit-terra
  - pyscf
  - h5py 
  - openfermion
  - openfermionpyscf
  - colorama
  - awscli
  - jaxlib
  - jax
  - distributed
  - dask