name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - jinja2==3.1.2
  - keras==2.12.0
  - markupsafe
  - matplotlib
  - oqpy==0.2.1
  - numpy==1.23
  - pandas
  - scipy
  - s3transfer
  - boto3==1.28.3
  - brotlipy==0.7.0
  - pip:
    - colorama >=0.2.5,<=0.3.7
    - awscli
    - docutils==0.14
    - botocore==1.31.4
    - distributed
    - msgpack-python
    - lz4
    - dask
    - pydantic==1.9.0 
    - amazon-braket-sdk==1.54.2
    - amazon-braket-schemas
    - amazon-braket-default-simulator==1.20.0
    - amazon-braket-pennylane-plugin==1.20.1
    - amazon-braket-algorithm-library==1.4.1
    - cvxpy==1.3.1
    - ecos==2.0.12
    - mypy-extensions==0.4.3
    - PennyLane-Lightning==0.31.0
    - pennylane==0.31.0 
    - pyscf
    - h5py >=2.8
    - openfermionpyscf==0.5
    - openfermion==1.5.1
    - jaxlib
    - jax==0.4.2
    - qiskit-aer==0.12.0
    - qiskit_braket_provider==0.0.4
    - qiskit-terra==0.23.3