name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - jinja2==3.1.2
  - keras==2.12.0
  - markupsafe
  - matplotlib
  - oqpy==0.2.1
  - numpy==1.23
  - pandas
  - scipy
  - s3transfer
  - botocore==1.31.4
  - boto3==1.28.3
  - amazon-braket-sdk==1.54.2
  - pennylane
  - colorama
  - awscli
  - lz4
  - brotlipy >=0.6.0
  - msgpack-python <1.0.0
  - docutils >=0.10,<0.15
  - distributed
  - dask==2023.1.1
  - pip:
    - pydantic==1.9.0 
    - amazon-braket-schemas==1.19.1
    - amazon-braket-default-simulator==1.20.0
    - amazon-braket-pennylane-plugin==1.20.1
    - amazon-braket-algorithm-library==1.4.1
    - cvxpy==1.3.1
    - ecos==2.0.12
    - mypy-extensions==0.4.3
    - PennyLane-Lightning==0.31.0
    - pyscf
    - h5py >=2.8
    - openfermionpyscf==0.5
    - openfermion==1.5.1
    - jaxlib
    - jax==0.4.2
    - qiskit-aer==0.12.0
    - qiskit_braket_provider==0.0.4
    - qiskit-terra==0.23.3