name: xeus-python-kernel 
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pydantic==1.8.2
  - botocore
  - awscli
  - boto3
  - amazon-braket-default-simulator
  - amazon-braket-pennylane-plugin
  - amazon-braket-schemas
  - amazon-braket-sdk
  - amazon-braket-algorithm-library
  - cvxpy
  - dask
  - ecos
  - jax
  - jinja2
  - keras
  - markupsafe
  - matplotlib
  - mypy-extensions
  - openfermion
  - openfermionpyscf
  - oqpy
  - numpy
  - pandas
  - pennylane
  - PennyLane-Lightning
  - qiskit-aer
  - qiskit_braket_provider
  - qiskit-terra
  - scipy
